### PR TITLE
Feature adv search bar AB#083

### PR DESCRIPTION
**Pull request by rikichoi**

### CODE REVIEW

**Review by EveJoyceStudent — COMMENTED** [review]
i'm not sure about the column display,
image
do we want the user to be able to hide the add player buttons, show the id and full name column, etc?

also i think we need to get the layout of this a bit neater, more like:
image
than the current:
image

**Comment by rikichoi** [comment]
Yeah no you're right, I'll have a look into it.

**Comment by EveJoyceStudent** [comment]
made some changes to simplify the code and deal with trailing zeroes in the win% search
@Riki225 you happy with the changes?

**Comment by rikichoi** [comment]
yep looks good!

**Review by EveJoyceStudent — APPROVED** [review]
great!

**Pull request merged**
